Symfony/src/Entity/Competition.php
<?php

namespace App\Entity;

use App\Repository\CompetitionRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: CompetitionRepository::class)]
class Competition
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['competition'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['competition'])]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['competition'])]
    private ?bool $is_active = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Wod $wod_in_progress = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getWodInProgress(): ?Wod
    {
        return $this->wod_in_progress;
    }

    public function setWodInProgress(?Wod $wod_in_progress): self
    {
        $this->wod_in_progress = $wod_in_progress;

        return $this;
    }
}

Symfony/src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Repository\CompetitionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{

    private $em, $cRepo;

    public function __construct(EntityManagerInterface $em, CompetitionRepository $cRepo) {
        $this->em = $em;
        $this->cRepo = $cRepo;
    }

    #[Route('/dashboard', name: 'app_dashboard')]
    public function index(): Response
    {
        /*$active_competition = $this->cRepo->findOneBy(["is_active" => true]);
        if($active_competition) {
            return $this->redirectToRoute("app_launch_competition", ["id" => $active_competition->getId()]);
        }*/

        $competitions = $this->cRepo->findAll();

        return $this->render('dashboard/index.html.twig', [
            'active_page' => 'dashboard',
            'competitions' => $competitions
        ]);
    }
}

Symfony/templates/dashboard/competition_add.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Ajouter une compétition</h1>
    </div>

    <div class="row">
        <div class="col-12">
            {{ form_start(form) }}
                {% if form_errors(form) %}
                    <div class="alert alert-danger">
                        {{ form_errors(form) }}
                    </div>
                {% endif %}

                <div class="row">
                    <div class="col-md-12">
                        {{ form_row(form.name) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 d-flex justify-content-center">
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                    </div>
                </div>
            {{ form_end(form) }}
        </div>

    </div>
{% endblock %}

Symfony/templates/dashboard/competition_display.html.twig
{% extends 'base_display.html.twig' %}
{% block body %}
    <div {{ vue_component('CompetitionDisplay') }}></div>
{% endblock %}

Symfony/templates/dashboard/competition_edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Editer la compétition - <strong>{{ competition.name }}</strong></h1>
    </div>

    <div class="row">
        <div class="col-12">
            {{ form_start(form) }}
                {% if form_errors(form) %}
                    <div class="alert alert-danger">
                        {{ form_errors(form) }}
                    </div>
                {% endif %}

                <div class="row">
                    <div class="col-md-12">
                        {{ form_row(form.name) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 d-flex justify-content-center">
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                    </div>
                </div>
            {{ form_end(form) }}
        </div>

        <hr class="divider my-0 col-12 mt-5 mb-5">

        <div class="col-12 d-flex justify-content-between">
            <h1 class="h3 mb-0 text-gray-800">WOD</h1>
            <a class="btn btn-success" href="{{path('app_add_wod', {competitionId: competition.id})}}">Ajouter un WOD</a>
        </div>

        {% for wod in wods %}
            <div class="col-md-4">
                <div class="card shadow mb-4">
                    <!-- Card Header - Dropdown -->
                    <div
                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">{{wod.name}}</h6>
                    </div>
                    <!-- Card Body -->
                    <div class="card-body">
                        <div>{{ wod.description }}</div>
                    </div>
                    <div class="card-footer d-flex justify-content-end">
                        <a class="btn btn-warning" href="{{path('app_edit_wod', {id: wod.id})}}"><i class="fas fa-pen fa-light fa-sm text-white-50"></i></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

Symfony/templates/dashboard/competition_launch.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="row">
        <div class="col-12">
            <div {{ vue_component('MyComponent', { 'id': competition.id }) }}></div>
        </div>
    </div>
{% endblock %}

Symfony/templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tableau de bord</h1>
        <a href="{{path('app_add_competition')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-plus fa-sm text-white-50"></i> Ajouter une compétition</a>
    </div>

    <!-- Content Row -->

    <div class="row">
        <!-- Area Chart -->
        {% for competition in competitions %}
        <div class="col-md-4">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary d-flex align-items-center"><span>{{competition.name}}</span>{% if competition.isActive %}<span class="badge badge-success text-xs ml-2">En cours</span>{% endif %}</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div>COMPETITION</div>
                </div>
                <div class="card-footer d-flex justify-content-end">
                    <a class="btn btn-success mr-2" href="{{path('app_launch_competition', {id: competition.id})}}"><i class="fas fa-eye fa-solid fa-sm text-white-50"></i></a>
                    <a class="btn btn-warning" href="{{path('app_edit_competition', {id: competition.id})}}"><i class="fas fa-pen fa-light fa-sm text-white-50"></i></a>
                </div>
            </div>
        </div>
        {% endfor %}        
    </div>
{% endblock %}